# Generated by Django 3.2.8 on 2021-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delevery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
