# Generated by Django 3.2.8 on 2021-12-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wish_list',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
