# Generated by Django 3.2.8 on 2021-12-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.flavor'),
        ),
    ]
