# Generated by Django 3.2.8 on 2021-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211210_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
