# Generated by Django 3.2.8 on 2021-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20211214_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='date_added',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='email_phone',
            new_name='phone',
        ),
    ]
