# Generated by Django 3.2.8 on 2021-12-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_contactus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='note',
            new_name='message',
        ),
    ]
